# Generated by Django 5.1.1 on 2024-11-22 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('adult', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='OregonTrail_V2.character')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='OregonTrail_V2.character')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='OregonTrail_V2.character')),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='OregonTrail_V2.character')),
                ('player5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='OregonTrail_V2.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evilChance', models.IntegerField()),
                ('name', models.TextField()),
                ('Dialogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OregonTrail_V2.dialogue')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField(blank=True)),
                ('currentGame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OregonTrail_V2.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OregonTrail_V2.profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='currentSeason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OregonTrail_V2.season'),
        ),
    ]
