# Generated by Django 5.1.1 on 2024-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OregonTrail_V2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
