# Generated by Django 5.1.1 on 2024-11-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OregonTrail_V2', '0002_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='text',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
