# Generated by Django 5.1.1 on 2024-11-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OregonTrail_V2', '0003_dialogue_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_id',
        ),
    ]
