# Generated by Django 5.1.1 on 2024-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OregonTrail_V2', '0005_remove_game_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='currentSeason',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall'), ('WINTER', 'Winter')], max_length=10),
        ),
    ]
