# Generated by Django 5.1.1 on 2024-12-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OregonTrail_V2', '0008_alter_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='currSeasonManager',
            new_name='season',
        ),
    ]
