# Generated by Django 5.1.1 on 2024-12-03 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OregonTrail_V2', '0010_remove_profile_currentgame_alter_game_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profileg', to='OregonTrail_V2.profile'),
            preserve_default=False,
        ),
    ]
