# Generated by Django 5.1.1 on 2024-12-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OregonTrail_V2', '0011_game_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='miles',
            field=models.IntegerField(default=0),
        ),
    ]
