# Generated by Django 5.1.1 on 2024-11-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voterID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
