# Generated by Django 5.1.1 on 2024-11-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_examples', '0003_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_person', to='db_examples.person')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_person', to='db_examples.person')),
            ],
        ),
    ]
