# Generated by Django 5.1.1 on 2024-10-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.AddField(
            model_name='image',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
